### ISSUE TITLE
Issue with album covers in 0.9.244

### ISSUE THREAD

**Issue by coxackie** [gnumdk/lollypop#1169]
### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: Arch

### Bug/Feature

After upgrading from 0.9.240 to 0.9.244 in Arch, the "Change Artwork" function does not seem to be working. Also, whenever when I choose "Save changes to files" in Preferences, next time I will open them it appears un-selected. I have all dependencies (including kid3-cli) installed.

-------------------------------
 Some terminal output: upon execution, I get 

/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()

When I open preferences:

DBusHelper::__on_get_proxy(): g-dbus-error-quark: Error calling StartServiceByName for org.gnome.Lollypop.Portal: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.gnome.Lollypop.Portal: Permission denied (23)
DBusHelper::__on_get_proxy(): g-dbus-error-quark: Error calling StartServiceByName for org.gnome.Lollypop.Portal: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.gnome.Lollypop.Portal: Permission denied (23)

When I press "Change artwork" at an album:

(lollypop:9006): Gtk-CRITICAL **: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

There are covers appearing (Google API set), but when I press one it does not update, and I get:

DBusHelper::__on_get_proxy(): g-dbus-error-quark: Error calling StartServiceByName for org.gnome.Lollypop.Portal: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.gnome.Lollypop.Portal: Permission denied (23)
-------------------------------

I see a lot of complaints about org.gnome.Lollypop.Portal. Not sure whether this is a problem of packaging in Arch - if you think it is, let me know and I will file a bug there.

 Cheers, and thanks for all your work,

 - Kostas.

**Comment by gnumdk** [comment]
Looks like the portal package is broken... Looks like an issue in arch package or in your linux...

**Comment by legacychimera247** [comment]
hope this is fixed as i have the same problem in fedora 26 too...covers are not working anymore...

**Comment by gnumdk** [comment]
So package may be broken too :-(

**Comment by coxackie** [comment]
FYI, after this bug was closed, I filed it in Arch, and the package maintainer said:

------------------------------
This is because of a bug in their new build system, lollypop-portal isn't +x anymore
------------------------------

Arch has resolved this issue.

I do, however, still get:

Gtk-CRITICAL **: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

in the terminal whenever I try to access artwork (although it works OK in Arch now).
